### ISSUE TITLE
Auth Headers for API requests needed for api.openshift

### ISSUE THREAD

**Issue by ryelo** [RedHatInsights/landing-page-frontend#300]
I tried to have a quick fix to attach the headers for all of the requests, but it broke on a fresh login/cleared cookies. I guess the requests were firing before the getUser() function was completed.

Rolled back my change and synced it to the branches, so app-services is still giving a 403 because of the auth headers.

I'll revisit this tomorrow, but if you have any ideas, lemme know. We can probably just call getToken() after getUser() and then use that for the header

**Comment by ryelo** [comment]
Tagging you guys so you see it in the morning 😄

**Comment by Hyperkid123** [comment]
@ryelo We can add the getToken call to the current user gate. Here it is: https://github.com/RedHatInsights/landing-page-frontend/blob/master/src/routes/Landing.js#L102. I will take a look later today.
